### PR TITLE
Fixed snyk vulnerability issue

### PR DESCRIPTION
**Pull request by RajanDhinoja**

### CODE REVIEW

**Comment by RajanDhinoja** [comment]
https://snyk.io/test/npm/xlsx/0.11.19

**Comment by RajanDhinoja** [comment]
@andy51002000 @NOTPOWERUSER @utwbackend can you please take a look into it and merge it?

**Comment by RajanDhinoja** [comment]
This should fix issue of #8

**Comment by RajanDhinoja** [comment]
Updated lodash version should also fix this
https://snyk.io/vuln/npm:lodash

**Comment by RajanDhinoja** [comment]
@andy51002000 @NOTPOWERUSER @utwbackend can you please take a look into it and merge it? It should fix all snyk vulnerability issues.

**Comment by RajanDhinoja** [comment]
@andy51002000 @NOTPOWERUSER @utwbackend  any update?

**Review by NoobTW — APPROVED** [review]

**Comment by RajanDhinoja** [comment]
@andy51002000 @NOTPOWERUSER  @utwbackend  any update?

**Comment by andy51002000** [comment]
Sorry for the late reply.
Your PR has been merged.

RajanDhinoja ***@***.***> 於 2021年4月10日 週六 下午3:22寫道：

**Pull request merged**
